### ISSUE TITLE
Doesn't work on my 1930 Model 15 Teletype

### ISSUE THREAD

**Issue by CuriousMarc** [deater/linux_logo#16]
Attachments: see video at https://youtu.be/2XLZ4Z8LpEE
Symptoms: When I try to print the linux_logo, it uses newfangled ASCII characters that are not compatible with the Baudot set on my 1930 vintage Model 15 Teletype which I use as a terminal. It also uses the newfangled ultra-wide 80 columns format, which overflows the standard 74 column width of The True Teletype.
Expected result: should be backwards compatible with 1930 technology, and print this Baudot/RTTY friendly logo instead:
```
                                                            $$$$$
                                                           $$$$$$$
               $                                           $$O$O$$
$$$$$$        $$$                                          $VVVVV$
  $$           $                                         $$  VVV  $$
  $$       $$$    $$$ $$$$   $$$    $$$  $$$$$ $$$$$    $          $$
  $$      $  $$    $$$    $$  $$     $$    $$   $$     $            $$
  $$     $   $$    $$     $$  $$     $$      $$$       $            $$$
  $$        $$$    $$     $$  $$     $$      $$$      QQ$           $$Q
  $$     $ $$$     $$     $$  $$     $$     $$ $$   QQQQQQ$       $QQQQQQ
  $$    $$ $$$ $   $$     $$  $$$   $$$    $$   $$  QQQQQQQ$     $QQQQQQQ
$$$$$$$$$$  $$$   $$$$   $$$$   $$$$ $$$ $$$$$ $$$$$  QQQQQ$$$$$$$QQQQQ

```
Estimated numbers of users affected by this: 1
therefore Importance = critical
I am OK if this would only work with the -curiousmarc option :-)
Cheers, keep up the good Linux software!

Marc

**Comment by deater** [comment]
OK, I've added the logo.  In theory now if you build with "make logos-all" and then the command line:
./linux_logo -w75 -a -LModel15-tty

it should work, although the system info display is probably using lowercase and other characters that might not print right

**Comment by CuriousMarc** [comment]
Thank you very much! I didn’t expect so much service!
Marc
